commonconfig:
  apkapth: "/Users/xinxi/Downloads/app_simul_6.1.0_20190425202227.apk"
  devicename: "192.168.56.101:5555"
  runtime: "1"

mailconfig:
  maillist: "xinxi1990@163.com"
  mailhost: "smtp.exmail.qq.com"
  mailuser: "xxxxx@xxxxx.com"
  mailpass:  "xxxxx"
  mailpostfix: "xxxxxx"

logincase:
  - action: "click"
    location: "By.ID,com.android.packageinstaller:id/permission_allow_button"
    time: 2
  - action: "click"
    location: "By.ID,com.android.packageinstaller:id/permission_allow_button"
    time: 2
  - action: "click"
    location: "By.ID,com.luojilab.player:id/btn_agree"
    time: 1


